name: Super Linter

on:
  push:

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Super Linter
        uses: super-linter/super-linter@v6.6.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
